[package]
name = "layer"
version = "0.0.0"
edition = "2024"
description = "Experimental primitives for Telegram MTProto layers and TL schemas"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/ankit-chaubey/layer"
keywords = ["telegram", "mtproto", "protocol"]
categories = ["network-programming"]
