[workspace]
resolver = "2"

members = [
    "layer-tl-parser",
    "layer-tl-gen",
    "layer-tl-types",
    "layer-crypto",
    "layer-mtproto",
    "layer",
    "layer-connect",
    "layer-client-core",   # ‚Üê new: high-level Client lives here
    "layer-client",
]

[workspace.package]
version     = "0.1.0"
edition     = "2021"
license     = "MIT OR Apache-2.0"
repository  = "https://github.com/yourname/layer"
