[workspace]
resolver = "2"

members = [
    "layer-tl-parser",
    "layer-tl-gen",
    "layer-tl-types",
    "layer-crypto",
    "layer-mtproto",
    "layer",
    "layer-connect",
    "layer-client",   # high-level Client library
    "layer-app",      # binary: login + send message
]

[workspace.package]
version     = "0.1.0"
edition     = "2024"
license     = "MIT OR Apache-2.0"
authors     = ["Ankit Chaubey <ankit@ankit-chaubey.com>"]
repository  = "https://github.com/ankit-chaubey/layer"
homepage    = "https://github.com/ankit-chaubey/layer"
