[package]
name        = "layer-bot"
description = "Showcase bot built with layer-client â€” demonstrates commands, keyboards, callbacks and more"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
authors.workspace    = true
repository.workspace = true
homepage.workspace   = true
publish = false

[[bin]]
name = "layer-bot"
path = "src/main.rs"

[dependencies]
layer-client  = { workspace = true }
layer-tl-types = { workspace = true }
tokio         = { version = "1", features = ["full"] }
env_logger    = "0.11"
log           = "0.4"
chrono        = { version = "0.4", features = ["clock"] }
