[package]
name        = "layer-tl-parser"
description = "Parser for Telegram's Type Language (.tl) schema files"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
