[package]
name        = "layer-client"
description = "High-level synchronous Telegram client â€” connect, auth, 2FA/SRP, send messages"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
authors.workspace    = true
repository.workspace = true
homepage.workspace   = true
readme               = "../../README.md"
keywords             = ["telegram", "mtproto", "client", "2fa", "bot"]
categories           = ["api-bindings", "network-programming"]

[dependencies]
layer-tl-types = { path = "../layer-tl-types", version = "0.1.0", features = ["tl-api", "tl-mtproto"] }
layer-mtproto  = { path = "../layer-mtproto",  version = "0.1.0" }
getrandom      = "0.2"
flate2         = "1"
num-bigint     = "0.4"
num-traits     = "0.2"
sha2           = "0.10"
hmac           = "0.12"
pbkdf2         = "0.12"
