[package]
name        = "layer-client"
description = "Telegram client: login and send messages â€” built on layer-client-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "layer-client"
path = "src/main.rs"

[dependencies]
layer-client-core = { path = "../layer-client-core" }
